title: Russian Cultural Exchange
email: russianculturalexchange@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rcemtl.github.io"
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title

markdown: kramdown

defaults:
    - {scope: {path: ""}, values: {layout: "post"}}


prose:
  rooturl: '_posts'
  siteurl: 'http://rcemtl.github.io'
  media: 'img'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "The image will be used as a background cover for the post. An easy way to upload the image is to drop it into post and then get it’s link."
          placeholder: "img/my_image.jpg"
          type: "url"
      - name: "facebook"
        field:
          element: "text"
          label: "Facebook url"
          help: "Link to the facebook post. That will insert facebook post at the bottom of the page."
          placeholder: "https://www.facebook.com/20531316728/posts/10154009990506729/"
          type: "url"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Enable comments"
          help: "This will enable commentaries for the post"
          value: true
