title: MIRCA
tagline: Morgan Initiative for<br/> Russian Cultural Affairs
email: russianculturalexchange@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Russian Cultural Exchange is a startup initiative that promotes Russian culture in Montreal. It works with local businesses from the Russian-speaking world to create a place where Russian speakers and enthusiasts can mingle, network and share information about the Russian world, its culture and history. Our mission is to create a centre to facilitate a deeper understanding of the various aspects of the past and present Russian world. All events are open to students of Russian language, native Russians-speakers, francophones, anglophones, and anyone else who is interested in learning something about the Russian world. It is not necessary to know how to speak Russian in order to participate in our events. Our events include: bi-monthly Russian conversation club for all levels; culinary events; Russian holiday celebrations; literature readings and film screenings; speaker series featuring scholars from McGill University, Concordia University, UdeM, and UQAM who specialize in various aspects of Russian arts, culture and history.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rcemtl.github.io"
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title

markdown: kramdown

defaults:
    - {scope: {path: ""}, values: {layout: "post"}}


prose:
  rooturl: '_posts'
  siteurl: 'http://rcemtl.github.io'
  media: 'img'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "The image will be used as a background cover for the post. Can be absolute or relative URL."
          placeholder: "img/cover.jpg"
          type: "url"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Enable comments"
          help: "This will enable commentaries for the post"
          value: false
      - name: "when"
        field:
          element: "text"
          label: "When"
          help: "The date of the event"
          placeholder: "YYYY-MM-DD HH:MM"
          type: "CURRENT_DATETIME"
      - name: "where"
        field:
          element: "text"
          label: "Where"
          help: "The place of the event"
          placeholder: "Name/address of the place"
          type: "text"
          value: "Anticafé Montréal, 294, rue Sainte-Catherine Ouest, H2X 2A1, Montréal QC"
      - name: "facebook"
        field:
          element: "text"
          label: "Facebook url"
          help: "Link to the facebook post. That will insert facebook post at the bottom of the page."
          placeholder: "https://www.facebook.com/20531316728/posts/10154009990506729/"
          type: "url"
      - name: "eventbrite"
        field:
          element: "text"
          label: "Eventbrite url"
          help: "Link to the eventbrite event. That will insert eventbrite widget at the bottom of the page."
          placeholder: "https://www.eventbrite.ca/e/traditional-russian-tea-ceremony-tickets-25958220737"
          type: "url"
